# Generated by Django 3.2.12 on 2022-12-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reminder_board_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
